---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: "Asia/Tokyo"
    labels:
      - dependabot
    pull-request-branch-name:
      separator: "_"
    commit-message:
      prefix: "chore(dependabot): "
