---
version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: daily
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "bump(bun)"
    commit-message:
      prefix: "chore(bun): "

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: "Asia/Tokyo"
    labels:
      - dependabot
      - "bump(github-actions)"
    commit-message:
      prefix: "chore(github-actions): "
