rules:
  sentence-length:
    max: 140
  max-ten:
    max: 5
  max-kanji-continuous-len:
    max: 6
    allow:
      - 第三者配信事業者
      - 自立支援医療制度
      - 障害者基礎年金
  preset-jtf-style:
    "2.1.8.算用数字": false
    "2.2.2.算用数字と漢数字の使い分け": false
    "3.1.1.全角文字と半角文字の間": false
  no-mix-dearu-desumasu:
    preferInHeader": ""
    preferInBody": "ですます"
    preferInList": "である"
    strict": true
  ja-no-mixed-period:
    periodMark: "。"
    allowPeriodMarks:
      - "："
      - "、"
    forceAppendPeriod: true
  no-dropping-the-ra: true
  no-doubled-conjunction: true
  no-doubled-joshi:
    min_interval: 1
  no-nfd: true
  "@textlint-rule/no-invalid-control-character": true
  no-zero-width-spaces: true
  no-exclamation-question-mark:
    allowHalfWidthExclamation: false
    allowHalfWidthQuestion: false
    allowFullWidthExclamation: true
    allowFullWidthQuestion: true
    allow: []
  ja-no-successive-word:
    allowOnomatopee: true
    allow:
      - "/[\\u2000-\\u2DFF\\u2E00-\\u33FF\\uF900-\\uFFFD]/"
  ja-no-abusage: true
  ja-no-redundant-expression: true
  ja-unnatural-alphabet: true
  "@textlint-rule/textlint-rule-no-unmatched-pair": true
  prh:
    rulePaths:
      - .prh.yaml
